name: Build assets

on:
    push:
        branches:
            - main
            - develop
        paths:
            - 'css/scss/**'
            - 'js/**/*.js'
            - '!js/*.min.js'
            - '!css/*.min.css'

jobs:
    build:
        uses: Evarisk/Saturne/.github/workflows/build-assets-reusable.yml@main
        with:
            module: reedcrm
